packages:
  - apps/*
  - packages/*
catalog:
  "@biomejs/biome": 2.0.4
  "@cloudflare/vitest-pool-workers": 0.8.43
  "@hono/zod-validator": 0.7.0
  "@types/node": 22.15.32
  hono: 4.8.2
  wrangler: 4.20.5
  lefthook: 1.11.14
  miniflare: 4.20250617.3
  typescript: 5.8.3
  vite: 6.3.5
  vitest: 3.2.4
  zod: ^3.23.8
