packages:
  - apps/*
  - packages/*
catalog:
  "@biomejs/biome": 1.9.4
  "@cloudflare/vitest-pool-workers": 0.8.15
  "@hono/zod-validator": 0.4.3
  "@types/node": 22.14.1
  hono: 4.7.6
  wrangler: 3.114.6
  lefthook: 1.11.10
  miniflare: 4.20250409.0
  typescript: 5.8.3
  vite: 6.2.6
  vitest: 3.1.1
  zod: ^3.23.8
