packages:
  - apps/*
  - packages/*
catalog:
  "@biomejs/biome": 1.9.4
  "@cloudflare/vitest-pool-workers": 0.8.16
  "@hono/zod-validator": 0.4.3
  "@types/node": 22.14.1
  hono: 4.7.7
  wrangler: 4.12.0
  lefthook: 1.11.10
  miniflare: 4.20250416.0
  typescript: 5.8.3
  vite: 6.3.1
  vitest: 3.1.1
  zod: ^3.23.8
