packages:
  - apps/*
  - packages/*
catalog:
  "@biomejs/biome": 1.9.2
  "@cloudflare/vitest-pool-workers": ^0.5.7
  "@hono/zod-validator": ^0.2.2
  "@types/node": ^22.5.5
  hono: 4.6.2
  wrangler: ^3.78.7
  lefthook: ^1.7.15
  miniflare: ^3.20240909.4
  typescript: ^5.6.2
  vite: ^5.4.7
  vitest: 2.1.1
  zod: ^3.23.8
