packages:
  - apps/*
  - packages/*
catalog:
  "@biomejs/biome": 2.1.4
  "@cloudflare/vitest-pool-workers": 0.8.56
  "@hono/zod-validator": 0.7.2
  "@types/node": 22.17.1
  hono: 4.9.0
  wrangler: 4.28.1
  lefthook: 1.12.2
  miniflare: 4.20250803.0
  typescript: 5.8.3
  vite: 7.1.1
  vitest: 3.2.4
  zod: ^3.23.8
