packages:
  - apps/*
  - packages/*
catalog:
  "@biomejs/biome": 1.9.4
  "@cloudflare/vitest-pool-workers": 0.8.34
  "@hono/zod-validator": 0.5.0
  "@types/node": 22.15.32
  hono: 4.8.0
  wrangler: 4.20.3
  lefthook: 1.11.14
  miniflare: 4.20250617.1
  typescript: 5.8.3
  vite: 6.3.5
  vitest: 3.2.4
  zod: ^3.23.8
