packages:
  - apps/*
  - packages/*
catalog:
  "@biomejs/biome": 2.1.1
  "@cloudflare/vitest-pool-workers": 0.8.53
  "@hono/zod-validator": 0.7.0
  "@types/node": 22.16.3
  hono: 4.8.4
  wrangler: 4.24.3
  lefthook: 1.12.2
  miniflare: 4.20250709.0
  typescript: 5.8.3
  vite: 7.0.4
  vitest: 3.2.4
  zod: ^3.23.8
