packages:
  - apps/*
  - packages/*
catalog:
  "@biomejs/biome": 2.2.3
  "@cloudflare/vitest-pool-workers": 0.8.61
  "@hono/zod-validator": 0.7.2
  "@types/node": 22.18.0
  hono: 4.9.6
  wrangler: 4.34.0
  lefthook: 1.12.4
  miniflare: 4.20250902.0
  typescript: 5.8.3
  vite: 7.1.5
  vitest: 3.2.4
  zod: ^3.23.8
