packages:
  - apps/*
  - packages/*
catalog:
  "@biomejs/biome": 1.9.4
  "@cloudflare/vitest-pool-workers": 0.5.31
  "@hono/zod-validator": 0.4.3
  "@types/node": 22.14.1
  hono: 4.7.4
  wrangler: 3.114.1
  lefthook: 1.11.3
  miniflare: 3.20250310.0
  typescript: 5.8.2
  vite: 6.2.1
  vitest: 2.1.9
  zod: ^3.23.8
