packages:
  - apps/*
  - packages/*
catalog:
  "@biomejs/biome": 2.2.4
  "@cloudflare/vitest-pool-workers": 0.9.3
  "@hono/zod-validator": 0.7.2
  "@types/node": 22.18.6
  hono: 4.9.8
  wrangler: 4.38.0
  lefthook: 1.13.1
  miniflare: 4.20250917.0
  typescript: 5.8.3
  vite: 7.1.6
  vitest: 3.2.4
  zod: ^3.23.8
