packages:
  - apps/*
  - packages/*
catalog:
  "@biomejs/biome": 1.9.4
  "@cloudflare/vitest-pool-workers": 0.8.34
  "@hono/zod-validator": 0.5.0
  "@types/node": 22.15.29
  hono: 4.7.11
  wrangler: 4.19.1
  lefthook: 1.11.13
  miniflare: 4.20250525.1
  typescript: 5.8.3
  vite: 6.3.5
  vitest: 3.2.1
  zod: ^3.23.8
