packages:
  - apps/*
  - packages/*
catalog:
  "@biomejs/biome": 1.9.4
  "@cloudflare/vitest-pool-workers": 0.5.31
  "@hono/zod-validator": 0.4.1
  "@types/node": 22.13.7
  hono: 4.6.20
  wrangler: 3.107.2
  lefthook: 1.10.10
  miniflare: 3.20250129.0
  typescript: 5.8.2
  vite: 6.0.11
  vitest: 2.1.9
  zod: ^3.23.8
