packages:
  - apps/*
  - packages/*
catalog:
  "@biomejs/biome": 1.8.3
  "@cloudflare/vitest-pool-workers": ^0.4.24
  "@hono/zod-validator": ^0.2.2
  "@types/node": ^20.9.0
  hono: ^4.5.7
  wrangler: ^3.72.1
  lefthook: ^1.7.14
  miniflare: ^3.20240806.1
  turbo: ^2.0.14
  typescript: ^5.5.4
  vite: ^5.4.2
  vitest: 1.5.0
  zod: ^3.23.8
