packages:
  - apps/*
  - packages/*
catalog:
  "@biomejs/biome": 1.9.4
  "@cloudflare/vitest-pool-workers": 0.8.30
  "@hono/zod-validator": 0.5.0
  "@types/node": 22.15.24
  hono: 4.7.10
  wrangler: 4.16.1
  lefthook: 1.11.13
  miniflare: 4.20250523.0
  typescript: 5.8.3
  vite: 6.3.5
  vitest: 3.1.4
  zod: ^3.23.8
