packages:
  - apps/*
  - packages/*
catalog:
  "@biomejs/biome": 2.0.6
  "@cloudflare/vitest-pool-workers": 0.8.49
  "@hono/zod-validator": 0.7.0
  "@types/node": 22.16.0
  hono: 4.8.4
  wrangler: 4.23.0
  lefthook: 1.11.16
  miniflare: 4.20250617.5
  typescript: 5.8.3
  vite: 7.0.3
  vitest: 3.2.4
  zod: ^3.23.8
