packages:
  - apps/*
  - packages/*
catalog:
  "@biomejs/biome": 1.9.4
  "@cloudflare/vitest-pool-workers": 0.8.18
  "@hono/zod-validator": 0.4.3
  "@types/node": 22.15.2
  hono: 4.7.7
  wrangler: 4.12.1
  lefthook: 1.11.11
  miniflare: 4.20250417.0
  typescript: 5.8.3
  vite: 6.3.3
  vitest: 3.1.2
  zod: ^3.23.8
