packages:
  - apps/*
  - packages/*
catalog:
  "@biomejs/biome": 1.9.4
  "@cloudflare/vitest-pool-workers": 0.8.26
  "@hono/zod-validator": 0.5.0
  "@types/node": 22.15.17
  hono: 4.7.9
  wrangler: 4.14.4
  lefthook: 1.11.12
  miniflare: 4.20250507.0
  typescript: 5.8.3
  vite: 6.3.5
  vitest: 3.1.3
  zod: ^3.23.8
