packages:
  - apps/*
  - packages/*
catalog:
  "@biomejs/biome": 1.9.4
  "@cloudflare/vitest-pool-workers": 0.5.28
  "@hono/zod-validator": 0.4.1
  "@types/node": 22.9.0
  hono: 4.6.10
  wrangler: 3.87.0
  lefthook: 1.8.2
  miniflare: 3.20241106.0
  typescript: 5.6.3
  vite: 6.0.0-beta.10
  vitest: 2.1.5
  zod: ^3.23.8
