packages:
  - apps/*
  - packages/*
catalog:
  "@biomejs/biome": 1.9.4
  "@cloudflare/vitest-pool-workers": 0.8.22
  "@hono/zod-validator": 0.4.3
  "@types/node": 22.15.3
  hono: 4.7.8
  wrangler: 4.13.2
  lefthook: 1.11.12
  miniflare: 4.20250424.1
  typescript: 5.8.3
  vite: 6.3.3
  vitest: 3.1.2
  zod: ^3.23.8
