packages:
  - apps/*
  - packages/*
catalog:
  "@biomejs/biome": 1.9.4
  "@cloudflare/vitest-pool-workers": 0.5.31
  "@hono/zod-validator": 0.4.1
  "@types/node": 22.13.0
  hono: 4.6.20
  wrangler: 3.87.0
  lefthook: 1.8.2
  miniflare: 3.20241106.1
  typescript: 5.7.2
  vite: 6.0.11
  vitest: 2.1.8
  zod: ^3.23.8
