name = "auth"
compatibility_date = "2024-09-19"
compatibility_flags = ["nodejs_compat"]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"                                       # i.e. available in your Worker on env.DB
database_name = "edge-cms-auth-example"
database_id = "0227514f-f958-49a7-8d95-a70e466e8d43"

# [ai]
# binding = "AI"
