name = "auth"
main = "./src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]


[env.production.vars]
AUTH_SECRET = "test"
JWT_SECRET = "test"

[[env.production.kv_namespaces]]
binding = "KV"
id = "00000000000000000000000000000000"

[[env.production.r2_buckets]]
binding = "R2"
bucket_name = "r2-bucket"


[[env.production.d1_databases]]
binding = "DB"
database_name = "database"
database_id = "00000000-0000-0000-0000-000000000000"
