name = "sandbox"
compatibility_date = "2024-08-17"

[dev]
port = 8787
# [vars]
# MY_VAR = "my-variable"

[vars]
AUTH_SECRET = "test"
JWT_SECRET = "test"

[[kv_namespaces]]
binding = "KV"
id = "a840e781a3584292ad292d29bd312782"

[[r2_buckets]]
binding = "R2"
bucket_name = "edge-cms-bucket"

[[d1_databases]]
binding = "DB"                                       # i.e. available in your Worker on env.DB
database_name = "edgecms"
database_id = "e0b8df76-9e29-4087-85a9-61e649f1171a"
preview_database_id = "DB"

# [ai]
# binding = "AI"
