name = "remix-pages"

pages_build_output_dir = "./build/client"
compatibility_date = "2023-04-20"
services = [
    { binding = "API", service = "sandbox" },
    { binding = "AUTH", service = "auth" },
]


[vars]
MY_VAR = "test"

[dev]
port = 8789

[[d1_databases]]
binding = "DB"                                       # i.e. available in your Worker on env.DB
database_name = "edge-cms-auth-example"
database_id = "0227514f-f958-49a7-8d95-a70e466e8d43"
