name = "remix-cloudflare-workers-template"

main = "./server.ts"
workers_dev = true
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2023-04-20"
services = [{ binding = "API", service = "sandbox" }]

[dev]
port = 8788

[vars]
MY_VAR = "test"

[site]
bucket = "./build/client"

[build]
command = "npm run build"
